# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.18
# 
# >> macros
# << macros
%define keepstatic 1

Name:       libusb
Summary:    A library which allows userspace access to USB devices
Version:    0.1.12
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://sourceforge.net/projects/libusb/
Source0:    http://prdownloads.sourceforge.net/libusb/%{name}-%{version}.tar.gz
Source100:  libusb.yaml
Patch0:     libusb-0.1.12-libusbconfig.patch
Patch1:     libusb-0.1.12-memset.patch
Patch2:     libusb-0.1.12-openat.patch
Patch3:     libusb-0.1.12-wakeups.patch
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig


%description
This package provides a way for applications to access USB devices.


%package devel
Summary:    Development files for libusb
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description devel
This package contains the header files, libraries  and documentation needed to
develop applications that use libusb.


%package static
Summary:    Static library for libusb
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}-devel = %{version}-%{release}

%description static
This package contains the static library for libusb



%prep
%setup -q -n %{name}-%{version}

# libusb-0.1.12-libusbconfig.patch
%patch0 -p1
# libusb-0.1.12-memset.patch
%patch1 -p1
# libusb-0.1.12-openat.patch
%patch2 -p1
# libusb-0.1.12-wakeups.patch
%patch3 -p1
# >> setup
# << setup

%build
# >> build pre
# << build pre

%configure  \
    --enable-static

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install 

# >> install post
# << install post



%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig








%files
%defattr(-,root,root,-)
# >> files
%doc AUTHORS README  COPYING
%{_libdir}/*.so.*
# << files


%files devel
%defattr(-,root,root,-)
# >> files devel
%{_bindir}/libusb-config
%{_libdir}/pkgconfig/libusb.pc
%{_includedir}/*
%{_libdir}/*.so
# << files devel

%files static
%defattr(-,root,root,-)
# >> files static
%{_libdir}/*.a
# << files static

